# Generated by Django 6.0.5 on 2026-05-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='linked_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='web.customer'),
        ),
    ]
