# Generated by Django 6.0.5 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
    ]
