# Generated by Django 6.0.5 on 2026-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_quotationrequest_quotationrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
